export {default as Header} from "./header";
export {default as Home} from "./home";
export {default as Popup} from "./popup";
export {default as About} from "./about";
export {default as Team} from "./team";
export {default as Contact} from "./contact";
export {default as Services} from "./services";
export {default as Testimonials} from "./testimonials";
export {default as Footer} from "./footer";